name: yesmonkey
favicon: null
layout_spectrum: 0.8014012826606631
typography_spectrum: 0.09435714385472238
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2625079690478742
  lightness: 0.8459420434664935
  saturation: 0.22629027999937534
  rhythmicContrast: 0.20252455142326653
purpose: []
